"""
SHOELOTSKEY AUTOMATED TEST DATA CLEANUP
=======================================
This script removes automated E2E test artifacts from your database, including:
1. Dummy test orders (e.g. Order # E3FE31C5 or orders with Customer 'Guest')
2. Duplicate test expense records (e.g. injected 'Food (Daily) - Lunch' duplicates)

Usage:
  venv\\Scripts\\python.exe backend\\clean_test_data.py
"""

import sys
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)

try:
    from db import engine
    from sqlalchemy import text
except ImportError as e:
    print(f"[ERROR] Could not import database engine: {e}")
    sys.exit(1)

def main():
    print("\n" + "="*65)
    print("        SHOELOTSKEY SMS - TEST DATA CLEANUP TOOL")
    print("="*65 + "\n")

    with engine.begin() as conn:
        print("[1] Searching for dummy test order 'E3FE31C5' or 'Guest' orders...")
        
        # Delete items associated with dummy order if any table exists for items/services
        # Delete from orders table
        res = conn.execute(text("""
            DELETE FROM orders 
            WHERE order_number = 'E3FE31C5' 
               OR order_number LIKE '%E3FE%' 
               OR customer_id IN (SELECT customer_id FROM customers WHERE customer_name = 'Guest' OR contact_number = '0000000000')
        """))
        print(f"    -> Deleted {res.rowcount} dummy order record(s) from 'orders' table.")
        
        # Delete guest customer record
        res_cust = conn.execute(text("""
            DELETE FROM customers 
            WHERE customer_name = 'Guest' OR contact_number = '0000000000'
        """))
        print(f"    -> Deleted {res_cust.rowcount} dummy customer record(s) from 'customers' table.")

        print("\n[2] Checking for duplicate 'Food (Daily)' test expenses...")
        # Delete duplicate expenses generated during test runs (leaving at most 1 or deleting test Lunch entries created on 07/30/26)
        res_exp = conn.execute(text("""
            DELETE FROM expenses 
            WHERE category = 'Food (Daily)' AND notes = 'Lunch' AND amount = 250.00
            AND expense_id NOT IN (
                SELECT MIN(expense_id) FROM expenses WHERE category = 'Food (Daily)' AND notes = 'Lunch' AND amount = 250.00
            )
        """))
        print(f"    -> Removed {res_exp.rowcount} duplicate test expense record(s) from 'expenses' table.")
        
        # Also clean up any sample test logs generated by offline verification tests if necessary
        res_logs = conn.execute(text("""
            DELETE FROM audit_logs 
            WHERE details LIKE '%E3FE31C5%' OR details LIKE '%offline sync test%'
        """))
        print(f"    -> Removed {res_logs.rowcount} related test audit log record(s).")

    print("\n✅ SUCCESS: All dummy test records and duplicates have been wiped from your database!")
    print("="*65 + "\n")

if __name__ == "__main__":
    main()
